config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :posts
  resources :users
  
  root 'home#index'

  get 'auth/:provider/callback', to: "sessions#create"

  delete 'sign_out', to: "sessions#destroy", as: 'sign_out'

  resources :post  do
    resources :comments
  end

  resources :user  do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :title , :content
	has_many :comments
	mount_uploader :image, ImageUploader	
end

app/models/user.rb
class User < ApplicationRecord
	def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) ||
            create_user_from_omniauth(auth)
  end
  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name']
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
   end
   def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  def comment_params
      params.require(:comment).permit(:autor, :content)

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_auth
  def index
  	 @posts = Post.last(10)
  end
  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end
  def username(user)
    if user == nil
    var = User.find_by(id: user)
    else
      var ="anonimo"
    end
    return var
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def index
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    #@posts = Post.all
    @posts = Post.where(userid: session[:user_id])
  end
  def show
  end

  def new
     @post = Post.new
  end
  def edit
  end
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:userid, :image, :title, :content, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:omniauth] = auth.except 'extra'
    user = User.sign_in_from_omniauth auth
    session[:user_id] = user.id
    session[:user_name] = user.name
    redirect_to root_url, notice: "SIGNED IN"
  end
  def destroy
  	session[:user_name] = nil
   session[:user_id] = nil
   session[:omniauth] = nil
   redirect_to root_url, notice: "SIGNED OUT"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_date(date)
		date.strftime("Posted on %b, %m %Y - %H:%M")
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id]= user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def logged_in_user
    if !logged_in?
      redirect_to root_url, notice: "SIGNED IN"
    end
  end
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.text_field :post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Autor</th>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.autor %></td>
        <td><%= comment.content %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Autor:</strong>
  <%= @comment.autor %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<%= render partial: 'shared/posts'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/x-icon" href="favicon.ico" />
</head>
<body>
<%= render partial: 'shared/nav'%>
<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/pages/index.erb
<div>
  <h1>Bem vindo!</h1>
  <p>Escolha uma rede social para começar</p>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form.hidden_field :userid, :value => session[:user_id] %>
<div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title , size: 20 , class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content , class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>
  <div class="actions">
      <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', :back %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<table class="table table-striped">
  <thead>
    <tr>
    <th scope="col" width="150px">Date</th>
      <th scope="col" width="300px" >Title</th>
      <th scope="col" align="center">Edit Post</th>
     <!--<th></th>
      <th></th>
      <th colspan="3"></th>-->
    </tr>
  </thead>



  <tbody>
<% for post in @posts.reverse %>
      <tr>
   <td align="center"><%= post.date %></td>
        <td><%= link_to post.title, post %> </td>
        <!--<td><%= link_to 'Show', post %></td>-->
        <td align="center"><%= link_to 'Edit', edit_post_path(post) %></td>
       <!--<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Post', new_post_path %> | <%= link_to 'Back', :back %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>
<%= link_to 'Back', :back %>

app/views/posts/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <h1 class="mt-4"><%= @post.title %></h1>
        <p class="lead">
          by
          <a href="#">Name</a>
        </p>
        <hr>
        <p><%= post_date @post.date %></p>
        <hr>
        <%= image_tag(@post.image_url.to_s, size: "900x300", :class => "img-fluid rounded") %>
        <hr>
        <p align="justify"><%= @post.content %>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>
        <hr>
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <%= form_for([@post, @post.comments.build]) do |f| %>
            <div class="field">
    <%= f.text_field :autor, size: 20 , class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content , class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
            <% end %>
          </div>
        </div>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
<div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0"><%= comment.autor %></h5>
           <%= comment.content %>
          </div>
        </div>
<!--<%= link_to 'Apagar Comentario', [comment.post, comment],
               :confirm => 'Tem certeza?',
               :method => :delete %>-->
<% end %>
      </div>
    </div>
  </div>
<%
  if session[:user_id]
    link_to 'Edit', edit_post_path(@post)
    puts "|"
end
  %>
<%= link_to 'Back', :back %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar">
  <table align="center" width="90%"><tr><td>
     <div class="navbar-header">
      <a class="navbar-brand" href="/">Collaborative Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if session[:user_id] %>
        <li class="active">
        <%= link_to "All Posts", '/' %>
        </li>
        <li><%= link_to "Posted Posts", '/posts' %></li>
        <li>
              <%= link_to "New Post", '/posts/new' %>
        </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
 <% if session[:user_id] %>
<li><%= link_to "Sign out", 'sign_out', method: :delete %></li>
        <li>
<table width="250px" cellspacing=20 cellpadding=1 border="0"><tr>
<td>
</td>
<td align="center">Signed in as <b><%= session[:user_name] %></b></td><td align="center">
            <%= image_tag session[:omniauth]['info']['image'],width: '50', height: '50', :class => "img-circle" %>

          </td></tr></table>
        </li>
 <% else %>
       <li class="nav-item pull-right add-space"><%=link_to(image_tag("login_facebook.png", size: "130x30", alt: "Facebook"), "auth/facebook", :class=>"nav-link") %></li>
      <% end %>
      </ul>
</td>
</tr>
</table>
    </div>
  </div>
</nav>




app/views/shared/_posts.html.erb

<div class="container">
<% for post in @posts.reverse %>
  <div class="well">
      <div class="media">
  		<div class="media-body">
      <h4 class="media-heading"><%= post.title %></h4>
          	<%= image_tag(post.image_url.to_s, size: "400x150") %>
          <p class="text-right">By Name</p>
          <p align="justify">
          	<%= truncate(post.content, :length => 7400) %> <%= link_to '[read more]', post %>
          </p>
          <ul class="list-inline list-unstyled">
  			<li><span><i class="glyphicon glyphicon-calendar"></i><%= post_date post.date %> </span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-comment"></i> <%= post.comments.count %> comments</span>
			</ul>
       </div>
    </div>
  </div>
    <% end %>
</div>